### ISSUE TITLE
Reorder logs in html view

### ISSUE THREAD

**Issue by nicholas512** [geocryology/sensorDb#2]
Logs are in ascending date order.  More convenient would be descending date order.

Adding `SORT BY timestamp ASC` in  sensorDb-jdbc/src/main/java/ca/carleton/gcrc/sensorDb/jdbc/DbApiJdbc.java doesn't seem to do it.  Missing something...

![image](https://user-images.githubusercontent.com/15223327/114084519-45d7bd80-987e-11eb-8819-ea8f2dcca58d.png)

**Comment by hgmacc** [comment]
This issue has been resolved. Logs now present in descending (date) order on this branch. 
![Screen Shot 2021-07-16 at 10 23 30 AM](https://user-images.githubusercontent.com/59845773/125962936-d927b22d-17e2-4eec-af0b-3bfb2d0bf765.png)
